/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#454747',
        'on-secondary-container': '#616363',
        'secondary': '#5d5f5f',
        'primary-fixed-dim': '#b4c5ff',
        'secondary-container': '#dfe0e0',
        'surface-container-low': '#eff4ff',
        'on-primary-fixed-variant': '#003ea8',
        'tertiary-fixed': '#dae2fd',
        'tertiary': '#4d556b',
        'secondary-fixed-dim': '#c6c6c7',
        'surface-dim': '#cbdbf5',
        'on-primary': '#ffffff',
        'outline': '#737686',
        'surface-variant': '#d3e4fe',
        'outline-variant': '#c3c6d7',
        'on-error-container': '#93000a',
        'surface-bright': '#f8f9ff',
        'inverse-primary': '#b4c5ff',
        'on-background': '#0b1c30',
        'secondary-fixed': '#e2e2e2',
        'surface': '#f8f9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-tint': '#0053db',
        'on-primary-container': '#eeefff',
        'on-surface': '#0b1c30',
        'tertiary-fixed-dim': '#bec6e0',
        'on-secondary-fixed': '#1a1c1c',
        'error': '#ba1a1a',
        'background': '#f8f9ff',
        'on-tertiary': '#ffffff',
        'primary-container': '#2563eb',
        'on-primary-fixed': '#00174b',
        'on-surface-variant': '#434655',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#3f465c',
        'on-tertiary-fixed': '#131b2e',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#dbe1ff',
        'error-container': '#ffdad6',
        'surface-container-high': '#dce9ff',
        'surface-container': '#e5eeff',
        'tertiary-container': '#656d84',
        'on-error': '#ffffff',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'primary': '#004ac6',
        'on-tertiary-container': '#eef0ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xl: '32px',
        '2xl': '48px',
        md: '16px',
        gutter: '24px',
        base: '4px',
        sm: '8px',
        '3xl': '64px',
        'container-max': '1440px',
        'sidebar-width': '280px',
        xs: '4px',
        lg: '24px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Inter'],
        'headline-sm': ['Inter'],
        'body-sm': ['Inter'],
        'headline-md': ['Inter'],
        'display-lg': ['Inter'],
        'headline-lg': ['Inter'],
        'label-sm': ['Inter'],
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'body-lg': ['Inter'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
